# Create env: conda env create -f environment.yml
name: datalab-env
dependencies:
  - python==3.7
  - pytest==5.2.2
  - scikit-learn==0.21.3
  - ipython
  - pip
  - pip:
    numpy==1.18.1
    scipy==1.3.2
    pandas==0.25.2
    scikit-learn==0.22.1
    urllib3==1.25.9
    xgboost==1.2.0
    typing-extensions==3.7.4.3
    kedro==0.16.1
    dill==0.3.1.1
    matplotlib==3.1.1