# Parameters Catalog

# HIGGS CHALLENGE
# General
index_col: EventId
weight_col: Weight
target_col: Label
cat_col:
  - PRI_jet_num
num_col:
  - DER_mass_MMC
  - DER_mass_transverse_met_lep
  - DER_mass_vis
  - DER_pt_h
  - DER_deltaeta_jet_jet
  - DER_mass_jet_jet
  - DER_prodeta_jet_jet
  - DER_deltar_tau_lep
  - DER_pt_tot
  - DER_sum_pt
  - DER_pt_ratio_lep_tau
  - DER_met_phi_centrality
  - DER_lep_eta_centrality
  - PRI_tau_pt
  - PRI_tau_eta
  - PRI_tau_phi
  - PRI_lep_pt
  - PRI_lep_eta
  - PRI_lep_phi
  - PRI_met
  - PRI_met_phi
  - PRI_met_sumet
  - PRI_jet_leading_pt
  - PRI_jet_leading_eta
  - PRI_jet_leading_phi
  - PRI_jet_subleading_pt
  - PRI_jet_subleading_eta
  - PRI_jet_subleading_phi
  - PRI_jet_all_pt

# Evaluation metric
higgs_scoring: accuracy

# Selection param (CV / test / val)
param_fold:
  nb_folds: 0
  method: standard
  test_size: 0.05
  val_size: 0.05

# Random forest params
param_rf_transform:
  params:
    sparse: False
    dtype: int
    impute_cat:
      missing_values: .NAN
      strategy: constant
      fill_value: -1
    impute_num:
      missing_values: .NAN
      strategy: mean
  feature_transform: cat_encode,impute
  target_transform: encoding
  n_label: 1

param_rf_transform_grid: {}

rf_param:
  n_jobs: 2
  min_samples_leaf: 100
  max_depth: 5
  n_estimators: 200

rf_param_grid:
  min_samples_leaf:
    - 50
    - 100
    - 500
    - 1000
  max_depth:
    - 3
    - 5
    - 10
  n_estimators:
    - 100
    - 250
    - 500

# XGBOOST params: eta: learning rate, gamma: min reduction loss to split, subsample: p dataset sampled,
# colsample_bytree: p col sampling, lambda: L2 reg coef, alpha: L1 reg coef
param_xgb_transform:
  params:
    sparse: False
    dtype: int
  feature_transform: cat_encode
  target_transform: encoding
  n_label: 1

param_xgb_transform_grid: {}

xgb_param:
  nthread: 2
  n_jobs: 2
  objective: binary:logistic
  colsample_bytree': 0.8
  subsample': 0.8
  eta: 0.1
  max_depth: 10
  alpha: 0
  lambda: 0
  min_child_leaf: 100
  gamma: 1
  n_estimators: 100

xgb_param_grid:
  colsample_bytree:
    - 0.5
    - 0.8
    - 1
  subsample:
    - 0.5
    - 0.8
    - 1
  eta:
    - 0.05
    - 0.1
    - 0.2
  max_depth:
    - 3
    - 5
    - 10
  lambda:
    - 0.01
    - 0.1
    - 0.5
  n_estimators:
    - 100
    - 300
    - 600

# DL params